### ISSUE TITLE
⚠️ Migration Docs for 5.0

### ISSUE THREAD

**Issue by amcdnl** [okta/okta-react#101]
Often there is breaking changes such as `restoreOriginalUri` in 5.0. There is no context to really what this change does ( either in the PR or the changelog ). 

We need to have better documentation on why and how to upgrade. Take a look at how Angular does it here: https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-1

It also doesn't help that the actual tracking of this is happening outside of Github Issues where there is no community visibility.

**Comment by mraible** [comment]
This might help: https://github.com/okta/okta-react#migrating-between-versions

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
There is a section in readme about migration to 5.0: [Migrating from 4.x to 5.x](https://github.com/okta/okta-react#migrating-from-4x-to-5x)
Resaon for introducing `restoreOriginalUri` - decoupling from `react-router` and ability to use `@reach/router`([issue for this](https://github.com/okta/okta-react/issues/81))

**Comment by amcdnl** [comment]
Gotcha - Thanks - I did not even know about that - feels like that would be better served in the change log though.

**Comment by JeffBeltran** [comment]
Might be worth pointing out that the guide at https://developer.okta.com/code/react/okta_react_sign-in_widget. I know it says at the top it's for `@okta/okta-react v4.1.0` but the guide has you install via `npm install @okta/okta-signin-widget`, which would install the latest version... took me a bit to find my issue
