### ISSUE TITLE
Issue passing restoreOriginalUri to Security Component

### ISSUE THREAD

**Issue by mitchgillin** [okta/okta-react#107]
Versions: 
    @okta/okta-auth-js": "^4.8.0
    @okta/okta-react": "^5.1.1
    
I am trying to follow the developer tutorial for version 5 of okta-react, but I am running into an issue where the security component won't accept the `restoreOriginalUri` callback I am passing to it. It is the same callback method being created and passed in the documentation. 

CODE: 

```

import React from 'react';
import { createBrowserHistory } from 'history';
import { BrowserRouter, Route, Switch } from 'react-router-dom';

import { Security } from '@okta/okta-react';
import { OktaAuth, toRelativeUrl } from '@okta/okta-auth-js';

import oktaConfig from './Auth';
const oktaAuth = new OktaAuth(oktaConfig);

const App = () => {
  const hist = createBrowserHistory();

  const restoreOriginalUri = async (_oktaAuth, originalUri) => {
    hist.replace(toRelativeUrl(originalUri, window.location.origin));
  };

  return (
    <BrowserRouter history={hist}>
      <Security
        oktaAuth={oktaAuth}
        restoreOriginalUri={restoreOriginalUri}
        redirectUri={window.location.origin + '/login/callback'}
      >
        <Switch>
          <Route path="/" render={() => <Foo />} />
        </Switch>
      </Security>
    </BrowserRouter>
  );
}
```

However, I am still getting hit with the error message `AuthSdkError: No restoreOriginalUri callback passed to Security Component.`

Any help would be appreciated.

**Comment by mitchgillin** [comment]
After downgrading to version 4.1.0, I am able to at least render my app.

**Comment by mraible** [comment]
You can no longer have `<Router>` and `<Security>` in the same JSX. You need to have `<Router>` a level up. This blog post has been updated for Okta React 5.0 and might help.

https://developer.okta.com/blog/2020/12/16/react-login

**Comment by mitchgillin** [comment]
Got it; that solved it! Did I miss this in the documentation somewhere?

**Comment by mraible** [comment]
If it's documented, it's difficult to find. I stumbled upon this same issue myself. The [first code example in the README](https://github.com/okta/okta-react#creating-react-router-routes-with-class-based-components) has this, but it could probably use some comments or further explanation.

**Comment by mitchgillin** [comment]
Ah I see! Looks like the functional code example has it wrapped on the same level, but the class-based code example has the proper hierarchy.
