### ISSUE TITLE
Error: AuthApiError

### ISSUE THREAD

**Issue by dusan-dragon** [okta/okta-react#109]
Hi all our portals started to get this error: `Error: AuthApiError` . This started to happen after easter time. The solution is to clear cache in browser, however we need to clear it every day... any idea what is happening?

In the console it is saying that the request was blocked because of CORS 🤷‍♂️  We did not change anything in our portals code.

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
What request results in CORS error?

**Comment by dusan-dragon** [comment]
@denysoblohin-okta `Access to XMLHttpRequest at https://PROJECT_NAME.okta.com/oauth2/v1/keys from origin OUR_PORTAL_URL has been blocked by CORS policy No Access-Control-Allow-Origin header is present on the requested resource`

**Comment by denysoblohin-okta** [comment]
@dusan-dragon 
This is a known problem, discussed here:
https://github.com/okta/okta-auth-js/issues/679#issuecomment-815980312
The fix should be available soon.

**Comment by dusan-dragon** [comment]
Cool thank you.  I think we can close this one in favour of linked issue.

**Comment by sandeepemail71** [comment]
https://support.okta.com/help/s/question/0D51Y00007w9P8fSAE/implicitcallback-returning-authapierror-screen-in-single-sign-on?language=en_US

Please check this thread
