### ISSUE TITLE
Regression in v5.1.0: okta-auth-js is back as regular dependency

### ISSUE THREAD

**Issue by khitrenovich** [okta/okta-react#114]
One of the breaking changes in Okta-React v4 was switch to `okta-auth-js` as peer dependency. However, in the recent minor update (v5.1.0) `okta-react-js` was moved back from peer to regular dependencies (https://github.com/okta/okta-react/commit/67626d12fcc165403885f90caedefb6f8bca7379#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R43). Is this change intentional?

**Comment by robcaldecott** [comment]
Interesting. We need v5 of `okta-auth-js` for a `withCredentials` `fetch` change.

**Comment by shuowu** [comment]
@khitrenovich Thanks for reporting the issue!
Internal Ref: OKTA-389991

**Comment by khitrenovich** [comment]
@shuowu Do you have any update on that? This effectively causes webpack to pull 2 copies of `okta-node-js` by default, inflating the resulting bundle size (and potentially causing other unwanted effects).

Here is the source map of one of our webapp chunks. On the left you can see v4.8 (pulled from `okta-react`) and on the right there is v4.9.1 (pulled via direct dependency configuration, following `okta-react` installation instructions).

![image](https://user-images.githubusercontent.com/3424762/118165641-86cd6f80-b3f2-11eb-8747-1644204efe1f.png)

**Comment by shuowu** [comment]
@shuowu You can track this PR (https://github.com/okta/okta-react/pull/128), we'll release it in v5.1.3.

**Comment by shuowu** [comment]
Change released in [V6](https://github.com/okta/okta-react/releases/tag/okta-react-6.0.0). Close the issue.
