### ISSUE TITLE
[Question] Is it possible to use this without react router?

### ISSUE THREAD

**Issue by cmacdonnacha** [okta/okta-react#115]
I have a react app that has one single page with no other routing. Do I still need to use `react router` in order to use this SDK?

**Comment by shuowu** [comment]
@cmacdonnacha The okta-react SDK basically does two things from the `routing` standpoint. 
1) it provides `SecureRoute` to protect the resource from unauthorized access. 
2) it provides `LoginCallback` to handle okta-hosted login redirect.

Based on what you want to achieve, you can just use the `Security` component in this SDK to hook `authState` and `authService` to your app. Or you can just use [okta-auth-js](https://github.com/okta/okta-auth-js) (the upstream SDK of okta-react) to achieve more flexibility.

**Comment by cmacdonnacha** [comment]
Thanks @shuowu, just saw this bit here in the README

> Users of routers other than react-router can use useOktaAuth to see if a authState.isPending is false and authState.isAuthenticated is true. If both are false, you can send them to login via oktaAuth.signInWithRedirect(). See the implementation of <LoginCallback> as an example.

So it sounds like I can use the `useOktaAuth` hook in my `index.tsx` file to decide if the user should be allowed forward.

**Comment by shuowu-okta** [comment]
@cmacdonnacha That's true. Just keep in mind, you may need to use `LoginCallback` component or implement similar logic if you are working on okta-hosted signin scenario. You can find more details in the [sample app](https://github.com/okta/samples-js-react/tree/master/okta-hosted-login#okta-react--okta-hosted-login-example).

**Comment by cmacdonnacha** [comment]
Thanks @shuowu I do hope to use the [Okta Sign in Widget](https://developer.okta.com/code/react/okta_react_sign-in_widget/) as well.

From reading various React + Okta docs they all seem to specify the use of `react-router`. I didn't add it previously as I only have one page, but in order to make the integration a bit easier, would you say that it's now worth adding in?

**Comment by shuowu** [comment]
@cmacdonnacha It depends on the scenario you want to implement. Let me list some of them below:

1) okta-hosted signin, in this scenario, you start with a okta-hosted login form, then it redirects to your app when the sign-in process is done. In this case, you do need to handle the login redirect URL from okta. In this SDK, the `LoginCallback` Component handles the logic for you. You may need some routing logic if you want to use this component. You can definitely opt-out to handle the routing by yourself, using the LoginCallback component just makes the work easier.

2) self-hosted sign-in flow, in this scenario, you can host a sign-in widget component in your app, then it will handle the authentication and retrieve tokens for you, then the routing logic won't be necessary.

**Comment by cmacdonnacha** [comment]
Excellent thanks @shuowu for all the info. I'll decide whether to go with the okta hosted or self hosted flow and go from there. From reading [this](https://developer.okta.com/docs/concepts/hosted-vs-embedded/) it appears that the okta hosted option is preferred and overall more secure.

**Comment by cmacdonnacha** [comment]
Hey @shuowu, one last question, do you know if I have to npm install both [okta-react](https://www.npmjs.com/package/@okta/okta-react) and [okta-auth-js](https://www.npmjs.com/package/@okta/okta-auth-js) in order to get this to work in my React app or is installing [okta-react](https://www.npmjs.com/package/@okta/okta-react) enough?

**Comment by shuowu** [comment]
@cmacdonnacha 
> Do you know if I have to npm install both okta-react and okta-auth-js in order to get this to work in my React app or is installing okta-react enough?

you may still need to install okta-auth-js, as you need to inject the instance to the Security component/

> What does the library use to store the JWT on the client side? Cookies, session storage?

Session Storage is used as default token storage. You can still customize it with https://github.com/okta/okta-auth-js#storagemanager

> Can the library handle refresh tokens out of the box or is that something I have to manage myself?

Auto-renew is turned on by default. See details [here](https://github.com/okta/okta-auth-js#autorenew)

**Comment by cmacdonnacha** [comment]
Excellent thanks again @shuowu

**Comment by cmacdonnacha** [comment]
Hey @shuowu 

>Session Storage is used as default token storage. You can still customize it with https://github.com/okta/okta-auth-js#storagemanager

Just wondering if Session Storage is definitely used by default? I'm seeing the tokens stored in local storage and nothing in session storage.

![image](https://user-images.githubusercontent.com/9777763/118292618-bb175d80-b4d0-11eb-808a-29e8f84d6fc2.png)
