### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isPending' of null in SecureRoute.tsx

### ISSUE THREAD

**Issue by paultipper** [okta/okta-react#119]
I'm trying to implement OpenId authentication and the OAuth2.0 PKCE authorization flow in a React app using the Okta React SDK (specifically, version **5.1.1** of **@okta/okta-react**, and version **5.0.0** of **@okta/okta-auth-js**), but I'm gettting an `Uncaught TypeError: Cannot read property 'isPending' of null` error in the SecureRoute component. The return stack displayed in the Console window is as follows:

```
Uncaught TypeError: Cannot read property 'isPending' of null
    at SecureRoute (SecureRoute.tsx:78)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670)
    at performSyncWorkOnRoot (react-dom.development.js:22293)
    at scheduleUpdateOnFiber (react-dom.development.js:21881)
    at updateContainer (react-dom.development.js:25482)
    at react-dom.development.js:26021
    at unbatchedUpdates (react-dom.development.js:22431)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:26020)
    at Object.render (react-dom.development.js:26103)
    at Module.<anonymous> (index.js:28)
    at Module../src/index.js (index.js:30)
    at __webpack_require__ (bootstrap:851)
    at fn (bootstrap:150)
    at Object.1 (queries.js:96)
    at __webpack_require__ (bootstrap:851)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
```
Here is the code in my `index.js` component:

```javascript
import React from "react";
import ReactDOM from "react-dom";
import { IntlProvider } from "react-intl";
import { BrowserRouter as Router } from "react-router-dom";
import { QueryClient, QueryClientProvider } from "react-query";
import { ThemeProvider } from "@keyloop/react-core";
import { App } from "./App";
import "@cdk-uip/icons";

// Mock the API
if (
  process.env.NODE_ENV === "development" &&
  process.env.REACT_APP_BFF_URL === undefined
) {
  const { worker } = require("./mocks/browser");
  worker.start();
}

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
    },
  },
});

// Render the app
ReactDOM.render(
  <QueryClientProvider client={queryClient}>
    <IntlProvider locale="en-GB" defaultLocale="en-GB">
      <Router basename={process.env.PUBLIC_URL}>
        <ThemeProvider>
          <App />
        </ThemeProvider>
      </Router>
    </IntlProvider>
  </QueryClientProvider>,
  document.getElementById("root")
);
```
and my App.js component is as follows:
```javascript
import React from "react";
import { Route, useHistory } from "react-router-dom";
import { Container, makeStyles } from "@material-ui/core";
import { SecureRoute, Security, LoginCallback } from "@okta/okta-react";
import { OktaAuth, toRelativeUrl } from "@okta/okta-auth-js";
import { Home } from "./Home";
import { Order } from "./Order";
import { Sample } from "./Sample";
import { Invoice } from "./Invoice";

const oktaAuth = new OktaAuth({
  issuer: process.env.REACT_APP_IDP_URL,
  clientId: process.env.REACT_APP_IDP_CLIENTID,
  redirectUri: window.location.origin + "/login/callback",
});

// App styles
const useStyles = makeStyles((theme) => ({
  main: {
    // spacing(2) = 1rem (16px)
    padding: theme.spacing(2),
  },
}));

function App() {
  const classes = useStyles();
  const history = useHistory();
  const restoreOriginalUri = async (_oktaAuth, originalUri) => {
    history.replace(toRelativeUrl(originalUri, window.location.origin));
  };

  return (
      <Security oktaAuth={oktaAuth} restoreOriginalUri={restoreOriginalUri}>
        <Container className={classes.main} component="main">
          <Route path="/" exact={true} component={Home} />

          {/* Private routes require authentication */}
          <SecureRoute path="/order" exact component={Order} />
          <SecureRoute path="/sample" component={Sample} />
          <SecureRoute path="/invoice" component={Invoice} />

          <Route path='/login/callback' component={LoginCallback} />
        </Container>
      </Security>
  );
}

export { App };
```
The REACT_APP_IDP_URL and REACT_APP_IDP_CLIENTID environment variables are set to my Okta oauth2/default endpoint and application client ids respectively.

**Comment by shuowu** [comment]
@paultipper Thanks for reporting the issue! Please see the [migrating guide of okta-auth-js](https://github.com/okta/okta-auth-js#from-4x-to-5x), `isPending` has been removed from authState since v5, and it's using `null` to present the initial state.

**Comment by ryanmr** [comment]
> @paultipper Thanks for reporting the issue! Please see the [migrating guide of okta-auth-js](https://github.com/okta/okta-auth-js#from-4x-to-5x), `isPending` has been removed from authState since v5, and it's using `null` to present the initial state.

Hi Shuo Wu, the documentation for okta react doesn't really specify that the latest stable release of okta js isn't suitable for this library's current release. In addition, I don't think the migration guide is applicable to this situation on the package consuming side. It's more applicable to this package itself.

**Comment by tbarrettwilsdon** [comment]
Oh man, I'm glad I found this issue - thought I was going crazy. This seems like a fairly large breaking change to introduce with absolutely no mention in the [migrating from 4.x to 5.x](https://github.com/okta/okta-react#migrating-between-versions) section for this library, and in fact .isPending is referenced constantly throughout the readme. Making things even more confusing is that .isPending is still used by SecureRoute and several other built in components, throwing unfixable errors unless you catch and silence them proactively, which is what I've had to do. If nothing else, it seems like the bare minimum here would be to make it explicitly clear in this library (and not a single sentence on a completely different repo for a dependency) that isPending is no longer a viable way to test for authentication and that internal references to it will be fixed eventually.

**Comment by tbarrettwilsdon** [comment]
For posterity, here's a screenshot of the okta-react library itself throwing a TypeError because it can't read isPending from LoginCallback:

![image](https://user-images.githubusercontent.com/6508528/116920988-5717ae00-ac21-11eb-8690-f5541fb5b69e.png)

**Comment by mraible** [comment]
Okta React won't have support for Auth JS 5.0 until https://github.com/okta/okta-react/pull/120 is merged and released.

**Comment by paultipper** [comment]
@shuowu Would downgrading Auth JS to 4.x be a viable workaround for this issue?

**Comment by shuowu** [comment]
@paultipper okta-react currently still suppose to work with okta-auth-js 4.x, as you can see in okta-react 's package.json file. It supports okta-auth-js v5 by accident due to it can just consume the injected okta-auth-js instance. 

So please stay with okta-auth-js v4.x when you use okta-react, and only make the change when it officially supports okta-auth-js v5 (most probably in the next minor version update). You can also check it [here](https://github.com/okta/okta-react/blob/master/package.json#L43).

Also, one suggestion is to lock the okta-auth-js module with caret (^) to make sure that both major versions are compatible. Then upgrade both packages together when needed.

**Comment by oyemini-fortifieddata** [comment]
> @shuowu Would downgrading Auth JS to 4.x be a viable workaround for this issue?

I tried with 4.9 and it worked

**Comment by paultipper** [comment]
> > @shuowu Would downgrading Auth JS to 4.x be a viable workaround for this issue?
> 
> I tried with 4.9 and it worked

Great, thanks for that - I'll try downgrading Auth JS to 4.9. 👍

**Comment by denysoblohin-okta** [comment]
okta-react 5.1.2+ will check appropriate version of okta-auth-js
okta-react 6 is compatible with okta-auth-js 5
