### ISSUE TITLE
[Question] - Is it ok to have the config commited to source control?

### ISSUE THREAD

**Issue by cmacdonnacha** [okta/okta-react#126]
Is it ok to have the okta auth config in the client itself and committed to source control? Would a non-commited env file be more secure?

```
const config = {
  clientId: '{clientId}',
  issuer: 'https://${yourOktaDomain}/oauth2/default',
  redirectUri: 'http://localhost:8080/login/callback',
  scopes: ['openid', 'profile', 'email'],
  pkce: true
};
```

**Comment by mraible** [comment]
The client ID is like a license plate for a car. It's OK to store it in source control.

**Comment by cmacdonnacha** [comment]
Excellent thanks. Just wanted to make sure there's nothing sensitive we shouldn't be storing here.

**Comment by cmacdonnacha** [comment]
@mraible I assume it's also ok to have the `issuer` in here?

**Comment by mraible** [comment]
Yes.
