### ISSUE TITLE
Application reloads on token refresh with React OKTA sign in widget

### ISSUE THREAD

**Issue by amit70** [okta/okta-react#130]
okta-react: 3.0.10
okta-signin-widget: 3.9.2

Currently application is reloaded when it's trying to get the refresh access token, hence losing all the changes which is sent to the backend server. The app used to silently refresh and send the updated token, but recently its having this refresh issue.

I'm using .getAccessToken() method, which returns the promise, and if it detects a token has expired, it will refresh and return a new one. Reference: https://devforum.okta.com/t/do-i-need-to-manually-refresh-tokens-in-my-spa/8064

I have also enabled EA token rotation feature, but no luck.
https://developer.okta.com/docs/guides/refresh-tokens/refresh-token-rotation/

Any help would be appreciated.

**Comment by ey52fpv** [comment]
Can anyone provide a path for the resolution?

**Comment by paulsonantajo** [comment]
Same issue is there in,
"@okta/okta-auth-js": "^5.2.0",
"@okta/okta-react": "^6.0.0"

**Comment by ey52fpv** [comment]
As a workaround, I'm degraded to okta-react:"3.0.0" and okta-signin-widget:"3.9.0" and seems to work.

**Comment by crisrauber** [comment]
Same issue
"@okta/okta-auth-js": "^5.2.1",
"@okta/okta-react": "^6.0.0"

Anyone find a solution ?

**Comment by stevenmckinnon** [comment]
I'm facing the same issue even when updated to 5.5.0

``` json
"@okta/okta-auth-js": "5.5.0",
"@okta/okta-react": "6.2.0",
```

**Comment by lacsaba** [comment]
I have the same issue, re-render starts at the <Security /> component and forces all  children components to  re-render.
```json
"@okta/okta-auth-js": "^6.3.0",
"@okta/okta-react": "^6.4.3",
```

**Comment by IbrahimOmar91** [comment]
I'm having the same issue even with versions suggested before by @crisrauber 

Versions:
```
"@okta/okta-auth-js": "^5.5.0",
"@okta/okta-react": "^6.0.0",
```
configuration:
```
const oktaConfig = {
  issuer: "IDP_ISSUER",
  clientId: "CLIENT_ID",
  redirectUri: origin + "/implicit/callback",
  scopes: ["openid", "email", "profile", "groups"],
  tokenManager: {
      autoRenew: true,
      expireEarlySeconds: 60,
};
```

**Comment by chinanderm** [comment]
Not sure if this is related, but occasionally I'll get routed to my login route in the middle of an active session. Haven't paid attention to any token refresh messages in dev tools, but this is certainly a poor user experience.

**Comment by saymow** [comment]
@chinanderm the same is happening with me, have you found a fix for this?

**Comment by chinanderm** [comment]
@saymow Unfortunately no. I'm planning on setting up a test scenario with a bunch of logging to hopefully capture an occurrence of the event to see what happens. I can follow up once I've done that.

**Comment by saymow** [comment]
@chinanderm i would be glad. I'm really thinking on removing this wrapper and doing the auth stuff myself.

**Comment by cmonteiro128** [comment]
Anyone find any solutions to this?

**Comment by jaredperreault-okta** [comment]
@cmonteiro128 Do you observe this same behavior with a sample app? https://github.com/okta/okta-react/tree/master/samples

**Comment by cmonteiro128** [comment]
Hello,

We ended up finding the bug in our App. We had a wrapper around Okta's SecureComponent, and in that file we were violating the react/no-unstable-nested-components rule, which caused React to dump its state. Fixing this solved our issue

**Comment by saymow** [comment]
We managed to figure out what was our problem on our side, it was really silly actualy: 

When configuring this, remember to add the **offline_access** scope on the app okta settings and configure the refresh tokens. It seems that the wrapper fallbacks to the "basic" auth method when you dont have theses thing configured.

**Comment by chinanderm** [comment]
> When configuring this, remember to add the offline_access scope on the app okta settings and configure the refresh tokens. It seems that the wrapper fallbacks to the "basic" auth method when you dont have theses thing configured.

To add to/be more explicit about this:
1. The application (in Okta dashboard) needs to have the Refresh Token setting enabled
2. In Security > API, ensure `offline_access` is an allowed scope

Thanks @saymow
