### ISSUE TITLE
Typescript issue between okta-react and okta-auth-js

### ISSUE THREAD

**Issue by cmacdonnacha** [okta/okta-react#131]
When using the following code in my tsx file:

```
const oktaAuth: OktaAuth = new OktaAuth(oktaConfig);
<Security oktaAuth={oktaAuth} restoreOriginalUri={restoreOriginalUri}>
```

I am getting the following Typescript error:

```
Type 'import(".../node_modules/@okta/okta-auth-js/lib/browser/browser").default' is not assignable to type 'import(".../node_modules/@okta/okta-react/node_modules/@okta/okta-auth-js/lib/browser/browser").default'.
  Types of property 'token' are incompatible.
    Property 'renewTokensWithRefresh' is missing in type 'import(".../node_modules/@okta/okta-auth-js/lib/types/api").TokenAPI' but required in type 'import(".../node_modules/@okta/okta-react/node_modules/@okta/okta-auth-js/lib/types/api").TokenAPI'.  TS2322
```

When hovering over `oktaAuth` is defines it as `OktaAuthBrowser`. Should it not be just `OktaAuth`?

![image](https://user-images.githubusercontent.com/9777763/118812052-a0186500-b8a5-11eb-813e-17a9e4d861f8.png)

**Versions:**

```
okta-react: 5.1.2
okta-auth-js: 4.8.0
```

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for reaching out @cmacdonnacha.

It looks like you got multiple `okta-auth-js` versions installed (https://github.com/okta/okta-react/issues/114).
Would you mind trying installing okta-auth-js@4.9 as a direct dependency?

**Comment by cmacdonnacha** [comment]
That worked, thanks 👍
