### ISSUE TITLE
V6 Not on NPM

### ISSUE THREAD

**Issue by JuliaCBrown** [okta/okta-react#132]
Hey folks. We're looking to upgrade our version of okta-auth-js and the [readme here](https://github.com/okta/okta-react#migrating-from-5x-to-6x) lists v6 as the being compatible with it. However, I'm not seeing v6 live on npm https://www.npmjs.com/package/@okta/okta-react

When will the new version get published?

**Comment by amacleay-cohere** [comment]
Update on this would be very helpful, thank you! Looking to upgrade okta-auth-js and this blocks us.

**Comment by niloyc** [comment]
For now you can do the following as a workaround till its on npm
```
yarn add https://github.com/okta/okta-react.git
```
or
```
npm install https://github.com/okta/okta-react.git
```

**Comment by wegry** [comment]
For @niloyc to work in yarn 3 (might work with yarn 2 as well), I had to 

```
yarn add @okta/okta-react@okta/okta-react
```

**Comment by kyle-pollock** [comment]
Any update on this? My team would like to use the npm registry as well.

**Comment by coolgod** [comment]
Also, `@okta/okta-auth-js` is a dependency:
https://github.com/okta/okta-react/blob/7c9bb234ff5641d0127a97b75a846585df31e7ca/package.json#L43

But the README still says install it as a peer dependency:
https://github.com/okta/okta-react/blob/7c9bb234ff5641d0127a97b75a846585df31e7ca/README.md

Am I missing sth?

**Comment by rosbel** [comment]
My team is under a firewall that doesn't have access to github.com, so neither @niloyc or @wegry's workaround works. Any update on when this will be published to npm?

**Comment by shuowu** [comment]
@rosbel We are working on the release, it would be on NPM soon.

**Comment by shuowu** [comment]
Version 6 has been released on NPM! Close the issue.
