### ISSUE TITLE
Checking major version is weired

### ISSUE THREAD

**Issue by jinhongkim** [okta/okta-react#135]
I'm using okta-react v5.1.2 and okta-react-js 4.8.0 

After login to okta component error returned like `AuthSdkError: Passed in oktaAuth is not compatible with the SDK, okta-auth-js version 4.x is the current supported version.`

Seeing that aktaAuth.userAgent appened like below
```
    oktaAuth.userAgent = `${process.env.PACKAGE_NAME}/${process.env.PACKAGE_VERSION} ${oktaAuth.userAgent}`;<br class="Apple-interchange-newline">
```

and Splitting like below
```
    const majorVersion = oktaAuth?.userAgent?.split('/')[1]?.split('.')[0];
```

I checked on debug mode and see that userAgent values filled like : 
`@okta/okta-react/5.1.2 @okta/okta-react/5.1.2 okta-auth-js/4.9.2`

Based on splitting logic, majorVersion overwritten to `okta-react` and it failed from version check logic.

Am I wrong or Is the bugs?

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for the report @jinhongkim.

Non-modified `okta-auth-js` version agent string is expected to be captured before it is getting patched at [L#54](https://github.com/okta/okta-react/blob/master/src/Security.tsx#L54). Is there a chance you are rendering multiple `<Security>` components in your app?

**Comment by jinhongkim** [comment]
Thanks for quick answer, I only use one Security components under BrowserRouter like below
```
<BrowserRouter>
  <Security oktaAuth={oktaAuth} onAuthRequired={customAuthHandler} restoreOriginalUri={restoreOriginalUri}>
        <Switch>
          <Route path="/login" render={() => <Login config={oktaSignInConfig} />} />
          <Route path="/login/callback" component={LoginCallback} />
          {routes.map((route, i) => {
            const { path, component: Component, exact, meta } = route;
            const { titleId, auth } = meta;
            const WitchRoute = auth ? PrivateRoute : Route;
  
            return (
              <WitchRoute
                path={path}
                exact={exact}
                key={i}
                render={(props: any) => {
                  meta.titleId &&
                    (document.title = formatMessage({
                      id: titleId
                    }));
                  return <Component {...props} key={i} />;
                }}
              />
            );
          })}
        </Switch>
      </Security>
 </BrowserRouter>
    ```

**Comment by oleksandrpravosudko-okta** [comment]
Would you mind describing a rationale behind using multiple `<Security>` instances? (so we can see if it could be supported properly).
In meantime, you could try pining  okta-react to 5.1.1 (it does not have version compatibility check).

**Comment by jinhongkim** [comment]
I refactor my app to use single Security instance and it works fine :)
Thanks for your help
