### ISSUE TITLE
TypeScript definition implies `authState` cannot be null when it can

### ISSUE THREAD

**Issue by aarestad** [okta/okta-react#140]
## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

The type of `IOktaContext` implies that `authState` can never be `null`, when in fact it can be!

Here is the definition:

```
export interface IOktaContext {
    oktaAuth: OktaAuth;
    authState: AuthState;
    _onAuthRequired: OnAuthRequiredFunction;
}
```

## Expected behavior

`authState` should never be null, according to this definition.

## Minimal reproduction of the problem with instructions

```
const { authState } = useOktaAuth();
if (authState.isAuthenticated) { // <-- This will fail with a null reference error
  // do something
}
```

## Environment

- Package version: v6
- React version: v17
- Browser: Chrome
- OS: MacOS 11
- Node version (`node -v`): v12.21
- Other:

## Configuration

- Okta application type: OIDC

**Comment by DanielJoyce** [comment]
Ooof, this was in the v6 release notes, but they forgot to update the TS types.

**Comment by DanielJoyce** [comment]
https://developer.okta.com/docs/guides/sign-into-spa/react/add-signin-button/

Yeah this doc is wrong now then. nulls are terrible, why didn't they add a placeholder or default for authstate?

**Comment by denysoblohin-okta** [comment]
Internal ref: OKTA-409131

**Comment by denysoblohin-okta** [comment]
@aarestad @DanielJoyce Please check version `6.1.0`

**Comment by aarestad** [comment]
Thank you!
