### ISSUE TITLE
Login process gives me a blank page on the callback when running on sites other than localhost (dev server).

### ISSUE THREAD

**Issue by dean-dot-git** [okta/okta-react#160]
## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
The hosted login pops up normally, login and it stalls out on the following url and provides a blank page with **no errors** being reported in the console:

https://mydevserver.mycompany.com/clients/manager/implicit/callback?code=oQf9mVS9DQj0GyH-PPAwzsh0iBkC5TcqX4h8XKAB2Zc&state=ci4itXVvcjCfsZlvLHRdOs3oztHry6eIWB74XBqVWC4x08xkPfajFejio29o66nd

When running the same code locally on http://localhost:3000, the code works fine.

In both cases the Okta server reports a successful login.  **Not one** console.log I put in gets hit, like it doesn't get back to the app even though the url above indicates that it is trying.

## Expected behavior
code operates the same in all environments.

## Minimal reproduction of the problem with instructions

config:
![image](https://user-images.githubusercontent.com/86485757/129781586-4caa1a4a-9f30-45cc-a6bd-55e729698e59.png)

component with security in it:
![image](https://user-images.githubusercontent.com/86485757/129781783-e3c66239-9967-4f02-88ce-8048483ddb04.png)

    "@okta/okta-auth-js": "^5.3.1",
    "@okta/okta-react": "^6.1.0",

## Extra information about the use case/user story you are trying to implement
just trying to log a user in on a dev server.

## Environment

- Package version:  see above
- React version: 17
- Browser: Google Chrome  92.0.4515.159
- OS: Client OS is Windows 10, Server OS is Windows Server 2012 R2
- Node version (`node -v`):  node 10 devops, node 14 locally
- Other:

## Configuration
see picture above and this one:
![image](https://user-images.githubusercontent.com/86485757/129782930-bb07978c-c059-48bd-97d9-be89bc4b1534.png)
These urls match precisely with both sites.

- Okta application type:  SPA, React

**Comment by dean-dot-git** [comment]
hopefully I'm doing something just outright dumb that I just missed, but maybe I found a bug?

**Comment by shuowu** [comment]
@dean-dot-git It's probably because the Router cannot match the logout callback route, can you try adding `/clients/manager` to the `LOGIN_CALLBACK_URI`?

**Comment by dean-dot-git** [comment]
@shuowu - appreciate the suggestion.  That fixed it.  Glad it was something easy like that.
