### ISSUE TITLE
SecureRoute returns null

### ISSUE THREAD

**Issue by kellengreen** [okta/okta-react#173]
`<SecureRoute>` returns `null` after visiting an invalid `<LoginCallback>` page. 

This happens even if the user has already successful logged in.

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
`<SecureRoute>` returns  `null`.

## Expected behavior
`<SecureRoute>` should render its `children`.

## Minimal reproduction of the problem with instructions
Demo and steps to reproduce are located [here](https://github.com/kellengreen/okta#reproduce-secureroute-returns-null-bug).

## Environment

```
    "@okta/okta-auth-js": "5.8.0",
    "@okta/okta-react": "6.3.0",
    "react": "^17.0.2",
```

**Comment by kellengreen** [comment]
Still reproducing with `@okta/okta-auth-js=6.0.0` and `@okta/okta-react=6.4.2`.

**Comment by denysoblohin-okta** [comment]
@kellengreen Please try `okta-auth-js 6.1.0`. In this version `updateAuthState()` will be called when `handleLoginRedirect` fails (eg. because of invalid url)
