### ISSUE TITLE
@okta/okta-react Auth redirect for multiple open pages/tabs in a domain race condition

### ISSUE THREAD

**Issue by hillc5** [okta/okta-react#180]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior
With multiple tabs open to protected routes on the same domain, issuing `localStorage.clear()` causes issues when those tabs redirect at the same time, either redirecting to `/` or displaying either a `AuthSdkError: Unable to retrieve OAuth redirect params cookie` or `AuthSdkError: OAuth flow response state doesn't match request state`.

This is due to the shared localStorage by domain, and the fact that the secureRouterReferrerPath used in `ImplicitCallback` is a single key in localStorage as well.

Thus one page will overwrite that value, or remove it altogether at some point in the redirect/auth cycle.

## Expected behavior
It would be nice to come up with a way to store the originating referrer keyed off of some unique identifier (perhaps even full pathname) in localStorage so that there would be no chance of collision/race-conditions when multiple tabs in the same domain are going through the auth-redirect cycle.

## Minimal reproduction of the problem with instructions
Two protected components that check `isAuthenticated`, and trigger a `login` or `redirect` within the same render cycle.

issuing `localStorage.clear()` should produce the concurrent redirects/auth cycles

## Environment

- Package Version: @okta/okta-reactv1.1.0
- Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
- OS: MacOS High Sierra 10.13.6 (17G65)
- Node version (`node -v`): 8.11.3
- Other:

**Comment by denysoblohin-okta** [comment]
Closing the issue.
okta-auth-js 5.7.0 contains the fix for this issue. Please upgrade if you use older version.
Feel free to reopen if you still experience this problem on new versions.
