### ISSUE TITLE
[okta-react] SPA login causes full-page/app reload

### ISSUE THREAD

**Issue by lfurzewaddock** [okta/okta-react#181]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

- During dev testing using `webpack-dev-server`, attempting to login causes the app/browser web page to fully reload, during the authentication process, after `auth.redirect({ sessionToken: '{sampleSessionToken}'})`) is called *note that it is passed a sessionToken. However, the user is successfully authenticated. Perhaps this is caused by `webpack-dev-server` and would work in a production environment?
- Logout behaves as expected.

## Expected behavior

- Login should not cause the app/browser web page to fully reload, during the authentication process.
- Could this be related to [auth.redirect({ sessionToken: '{sampleSessionToken}'})](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#authredirectadditionalparams) which states if the auth.redirect function call is supplied a single object argument with a key 'sessionToken' and string value containing the 'Okta sessionToken', full-page redirect is bypassed.

## Minimal reproduction of the problem with instructions

The same behaviour is found in an Okta example project: [okta-node-react-registration-example](https://github.com/oktadeveloper/okta-node-react-registration-example).
However, for me the login link was not working but I worked around that by entering the path `http://localhost:3000/login`, directly into the browser address bar.

## Environment

- Package Version:
@okta/okta-react v1.0.2 & @okta/okta-react v1.1.4
- Browser:
Chrome v70 & MS Edge v44
- OS:
Windows 10 (WSL)
- Node version (`node -v`):
v8.11.2
- webpack-dev-server
v3.1.9

**Comment by eddiemonge** [comment]
@lfurzewaddock can this be closed?
