### ISSUE TITLE
Advice on tracking intermittent logout issue

### ISSUE THREAD

**Issue by tantilla** [okta/okta-react#189]
## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [x] Other (Describe below) - Question

Hello, 

Sorry for posting some questions here, but not getting responses in the forum.
I'm using a typical PKCE hosted login setup based on the demo, initialized once at the top of the app with the following:

   
@okta/okta-auth-js: "5.8.0"
@okta/okta-react": "6.1.0"

```

const okta = new OktaAuth({
    issuer: REACT_APP_ISSUER,
    clientId: REACT_APP_CLIENT_ID,
    redirectUri: window.location.origin + '/login/callback',
    pkce: true,
    tokenManager: {
        autoRenew: true
    }
});

const restoreOriginalUri = async (_oktaAuth, originalUri) => {
        history.replace(toRelativeUrl(originalUri || '/', window.location.origin));
};

 <Security oktaAuth={okta} restoreOriginalUri={restoreOriginalUri}>
  <Router history={history}>
                <Switch> 
                         <Route exact path='/login/callback'  \ \component={LoginCallback} />
                        <SecureRoute exact path='/documents' >
                               <DocumentsRoute />
                         </SecureRoute> 
...

```
        
For the most part we have had no issues, however after deploying to several environments some users are complaining about being intermittently logged out. I use the application daily and cannot reproduce the issue. To rule out typical session expiration I set the sign in policy to over 8 hrs and was able to go an entire day without hitting an expiration break point as expected.  At this point, I use so little of the API surface I am just learning what issues might be possible. I did convince one of the users to record an HTTP archive file and it shows a request made to the login URI made in the middle of a page that just has normal application logic.
There are support tickets here in the past that exhibit some of the characteristics, but they could be out dated. 

Without having gone through the github source yet, it is possible that signInWithRedirect() is getting triggered by some error ?

What is the best way to log Okta related events that might uncover this problem ?

Is it possible with some custom hook or component configuration to block the normal signout workflow with a guard so that its not triggered automatically ?

## Current behavior

User is intermittingly logged out

## Expected behavior

User is only logged out on session expiration

## Environment
- Package version:
- React version:17.0.2,
- Browser: Chrome, Firefox
- OS:
- Node version (`node -v`):
- Other:

## Configuration

- Okta application type: PKCE

**Comment by jaredperreault-okta** [comment]
Both `SecureRoute` and `LoginCallback` accept an `errorComponent` prop, which will render if an exception is thrown by an underline [auth-js](https://github.com/okta/okta-auth-js) method. You could implement these error components and perform additional logging, possibly recover from the error state.

See https://github.com/okta/okta-react/blob/master/src/SecureRoute.tsx#L81

**Comment by tantilla** [comment]
Thanks, I will try this.
