### ISSUE TITLE
Test cases failing in CI/CD - Cannot find module 'compare-versions' from '../node_modules/@okta/okta-react/bundles/okta-react.cjs.js'

### ISSUE THREAD

**Issue by amar-drivevariant** [okta/okta-react#192]
I have integrated the okta react in our application. 

## I'm submitting a:

- [x] Bug report  

FAIL templates/__tests__/App.spec.js
  ● Test suite failed to run

    Cannot find module 'compare-versions' from '../node_modules/@okta/okta-react/bundles/okta-react.cjs.js'

    Require stack:
      /github/workspace/node_modules/@okta/okta-react/bundles/okta-react.cjs.js
      templates/App.js
      templates/__tests__/App.spec.js

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/@okta/okta-react/bundles/okta-react.cjs.js:22:23)

In CI/CD it is throwing error module not found

## Expected behavior
Test cases in working on locally perfectly but in CI/CD it breaking.

## Environment

- Package version: "@okta/okta-react": "^6.2.0"
- React version: "react": "^17.0.2"
- Browser: Chrome
- OS:
- Node version (`node -v`): 14.17.0
- Other:

**Comment by garzito** [comment]
Getting similar error with missing `compare-versions` package but in okta-react.esm instead of okta-react.cjs.js.
Using Node version `v15.14.0`

**Comment by shuowu** [comment]
@amar-drivevariant @garzito 
Please try patch release [v6.4.1](https://github.com/okta/okta-react/releases/tag/okta-react-6.4.1), closing this issue for now, feel free to reopen it if the issue still exists.
