### ISSUE TITLE
Forcing ES Modules

### ISSUE THREAD

**Issue by crypto-yang** [okta/okta-react#20]
When using with Next.js and I call 

```js
import { useOktaAuth } from '@okta/okta-react';
```

Next.js/typescript will compile this to common.js and then Okta will through an error.

```
Error: Must use import to load ES Module: /Users/yangli/Documents/projects/apps/tax-client-ui/node_modules/@okta/okta-react/src/index.js
require() of ES modules is not supported.
require() of /Users/yangli/Documents/projects/apps/tax-client-ui/node_modules/@okta/okta-react/src/index.js from /Users/yangli/Documents/projects/apps/tax-client-ui/.next/server/pages/user/signin.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/yangli/Documents/projects/apps/tax-client-ui/node_modules/@okta/okta-react/package.json.
```

## Expected Behaviour 
It should allow both EsModules and Common.js, most UI package managers for UI is still using common.js for production.

**Comment by tamarasaurus** [comment]
I have the same issue, is there any workaround so far? (Besides not upgrading)  I wouldn't expect such a breaking change in a patch version

**Comment by crypto-yang** [comment]
@tamarasaurus for now we're just using an older version, otherwise you can have a script which runs on postinstall and removes this line of the okta-react package https://github.com/okta/okta-react/blob/master/package.json#L26

**Comment by vdineva** [comment]
Any update on this issue? This is blocking us from upgrading to webpack v5

**Comment by shuowu** [comment]
@vdineva okta-react starts support both es module and commonJS since version 4.0. (https://github.com/okta/okta-react/blob/master/package.json#L29)

As it's a major version bump, please also see the [Migrating guide](https://github.com/okta/okta-react#migrating-from-3x-to-4x) to update your application.

**Comment by shuowu** [comment]
Close the issue as both esm and cjs are supported in version 4.0 and above.
