### ISSUE TITLE
Process is not defined reference error

### ISSUE THREAD

**Issue by dnieuwmans** [okta/okta-react#202]
## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
We try to update our okta-react package to the latest version, from `6.3.0` to `6.4.1`. The app crashes and I see the following message in my console: `Uncaught ReferenceError: process is not defined`. This leads to: https://github.com/okta/okta-react/blob/57fa309f0366a92e0122f21d356de1e2130a1dd3/src/Security.tsx#L91 and this is in my understanding nothing brand new, right? I wonder why I got this message for version `6.4.1` and not for `6.3.0.` 

## Expected behavior
Page should load correctly without uncaught reference error.

## Minimal reproduction of the problem with instructions
Already described in current behavior. Updating from `6.3.0` to `6.4.1`.

## Extra information about the use case/user story you are trying to implement
N/A

## Environment

- Package version:
- React version: 17.0.2
- Browser: Chrome, Firefox, Edge
- OS: Windows 10
- Node version (`node -v`): 16.13.1

## Configuration

- Okta application type:

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for the report @dnieuwmans.

Did you have a chance to check if CRA/webpack [issue](https://github.com/facebook/create-react-app/issues/11771#issuecomment-998180463) might be affecting your setup?

**Comment by dnieuwmans** [comment]
Thanks for linking the issue, but I don't think it does, since we don't use CRA and made our own webpack config back in the day. We also didn't update any webpack packages when updating okta-react from 6.3.0 to 6.4.1. So I am a bit puzzled.

**Comment by oleksandrpravosudko-okta** [comment]
We are going to release a patch removing `process.env` reference from the bundle - thanks for bringing this up.

**Comment by shuowu** [comment]
@dnieuwmans Please try with v6.4.2. Closing this issue, please feel free to reopen it if the issue still exist.
