### ISSUE TITLE
SPA reloads when token refreshes

### ISSUE THREAD

**Issue by stevenmckinnon** [okta/okta-react#206]
## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
Similar to [issue/130](https://github.com/okta/okta-react/issues/130) except not using widget, just standard Okta login page.
When access token expires and updates in local storage, React app reloads losing user progress.

## Expected behavior
token refreshes without user impact

## Minimal reproduction of the problem with instructions
Change expiresAt in okta_token_storage for both idToken and accesToken
Set expiry in 2 minutes (use epoch converter - https://www.epochconverter.com/)

**Okta Security Component:**
``` typescript
function Security({ clientId, oktaURL, children }: ISecurityProps) {
  const history = useHistory();

  const config: OktaAuthOptions = {
    clientId,
    issuer: oktaURL,
    scopes: ["openid", "profile", "email"],
    pkce: true,
    redirectUri: `${window.location.origin}/login/callback`,
  };

  const restoreOriginalUri: RestoreOriginalUriFunction = async (_oktaAuth: OktaAuth, originalUri: string) => {
    history.replace(toRelativeUrl(originalUri, window.location.origin));
  };

  const oktaAuth = new OktaAuth(config);
  const onAuthRequired = (): void => history.push("/login");

  return (
    <OktaSecurity oktaAuth={oktaAuth} onAuthRequired={onAuthRequired} restoreOriginalUri={restoreOriginalUri}>
      {children}
    </OktaSecurity>
  );
```

## Extra information about the use case/user story you are trying to implement
N/A

## Environment

- Package version: "@okta/okta-auth-js": "5.9.1",
    "@okta/okta-react": "6.3.0",
- React version: 17.0.2
- Browser: Chrome
- OS: macOS
- Node version (`node -v`): 15.4.0
- Other:

## Configuration

- Okta application type:

**Comment by alfredvaa** [comment]
Same issue here, how did this get solved?

**Comment by mroche74** [comment]
I'm having this issue as well.  @stevenmckinnon can you indicate how this was resolved?
