### ISSUE TITLE
Is not compatible with react-router-dom ^6.3.0

### ISSUE THREAD

**Issue by reduxdj** [okta/okta-react#229]
### Describe the bug?

import { useOktaAuth } from '@okta/okta-react'; fails

### What is expected to happen?

to work

### What is the actual behavior?

fails

### Reproduction Steps?

follow documentation

### SDK Versions

  "@okta/okta-react": "^6.4.3",

### Execution Environment

localhost

### Additional Information?

doesn't work

**Comment by denysoblohin-okta** [comment]
Thanks for submitting the issue.
okta-react currently does not support react-router 6
 https://github.com/okta/okta-react/issues/178

**Comment by AkshatK805** [comment]
> Thanks for submitting the issue. okta-react currently does not support react-router 6 Closing as duplicate to #178

I'm trying to integrate okta with react js with react router v5. I'm able to log in to the application but as soon as I log in I get this message "AuthSdkError: Unable to parse a token from the url" and on refreshing the page this goes away and my expected component gets rendered after login callback component is called. Is this the intended behavior currently or am I missing something?

**Comment by denysoblohin-okta** [comment]
Looks like `oktaAuth.handleLoginRedirect()` in effect of `LoginCallback` component is called twice.
Do you create `OktaAuth` instance once and pass it to `Security` component ?
Can you provide minimum reproducible demo app with this issue?

**Comment by AkshatK805** [comment]
> 

I've correctly configured the properties in App.js and Have written the routing as :- 
<Security
        oktaAuth={oktaAuth}
        onAuthRequired={customAuthHandler}
        restoreOriginalUri={restoreOriginalUri}
      >
        <Routes>
          <Route path='/login' element={<Home />} />
          <Route path='/' element={<Header />} />
          <Route path = '/navbar' element = {<Navbar/>} />
            <Route exact path="/login/callback" element={<LoginCallback />} />
          </Routes>
      </Security>

And this is my Header.js code where I'm handling okta authentication as :- 
const { authState, oktaAuth } = useOktaAuth();
  const [userInfo, setUserInfo] = useState(null);

  const logout = async () => await oktaAuth.signOut();

  useEffect(() => {
    async function authenticate() {
      if (!authState)
        return;
      if (!authState.isAuthenticated) {
        await oktaAuth.signInWithRedirect();
      }
    }
    authenticate();
  }, [authState, oktaAuth]);

  useEffect(() => {
    if (!authState || !authState.isAuthenticated) {
      setUserInfo(null);
    } else {
      oktaAuth.getUser().then((info) => {
        setUserInfo(info);
      });
    }
  }, [authState, oktaAuth]);

With this I'm able to perform login and logout functionality but an initial render I get AuthSdk error and if I refresh the page the code works as it is expected. I'm using Open Id connect way.

**Comment by jaredperreault-okta** [comment]
@AkshatK805 can you confirm which react router version you're using? You mentioned `v5`, however the following snippet matches the `v6` api

> ```javascript
> <Route path='/login' element={} />
> <Route path='/' element={} />
> <Route path = '/navbar' element = {} />
> <Route exact path="/login/callback" element={} />
> ```

Also I suggest taking a look at our routing samples: https://github.com/okta/okta-react/tree/master/samples/routing

**Comment by AkshatK805** [comment]
> @AkshatK805 can you confirm which react router version you're using? You mentioned `v5`, however the following snippet matches the `v6` api
> 
> > ```js
> > <Route path='/login' element={} />
> > <Route path='/' element={} />
> > <Route path = '/navbar' element = {} />
> > <Route exact path="/login/callback" element={} />
> > ```
> 
> Also I suggest taking a look at our routing samples: https://github.com/okta/okta-react/tree/master/samples/routing

Can you suggest me how to work with react-router-dom v6 if you have any references/idea on that?
