### ISSUE TITLE
<SecureRoute render={() => 'derp'} /> always renders

### ISSUE THREAD

**Issue by nickanna42** [okta/okta-react#23]
okta-react v3.0.4

The following

    <SecureRoute render={() => 'derp'} />

always renders the `derp` string and does not force the user to the okta sign-in page

where as

    const DerpComponent = () => 'derp';
    
    <SecureRoute component={DerpComponent} />

doesnt render the `derp` string and does redirect the user to the okta sign-in page

**Comment by aarongranick-okta** [comment]
@nickanna42 I believe this issue was fixed in version [3.0.5](https://github.com/okta/okta-react/releases/tag/%40okta%2Fokta-react-3.0.5)

**Comment by nickanna42** [comment]
Thank you
