### ISSUE TITLE
"Failed to execute 'postMessage' on 'BroadcastChannel'" error - React 18

### ISSUE THREAD

**Issue by RikkiMasters** [okta/okta-react#232]
### Describe the bug?

Warning appears after upgrading to React 18, however, it still seems to function fine.

EDIT: Issue only present on React strict mode

```
native.js:26 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'BroadcastChannel': Channel is closed
    at Object.postMessage (http://localhost:8000/xxx/static/js/bundle.js:70352:21)
    at http://localhost:8000/xxx/static/js/bundle.js:69149:47
```
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/11843864/169278752-81cee255-d679-463d-a744-9b77666dea54.png">

Call stack
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/11843864/169279019-8e81a368-1e8a-4f27-a66b-76a48a8ff649.png">

### What is expected to happen?

No error

### What is the actual behavior?

Error but still functional

### Reproduction Steps?

```
import { OktaAuth } from "@okta/okta-auth-js";
import { Security } from "@okta/okta-react";
import { useSelector } from "react-redux";
import { useNavigate } from "react-router-dom";

// component must be within <BrowserRouter> for useNavigate to work
export const AuthWrapper = ({ children }) => {
  const { okta } = useSelector((state) => state.appConfig);
  const navigate = useNavigate();

  const oktaAuth = new OktaAuth({
    issuer: okta.issuer,
    clientId: okta.clientId,
    redirectUri: window.location.origin + "/xxx/login/callback",
    pkce: okta.pkceEnabled,
  });

  const restoreOriginalUri = async (_oktaAuth, originalUri) => {
    const routerBasename = "/" + window.location.pathname.split("/")[1];
    const relativeUri = originalUri.replace(routerBasename, "");
    navigate(relativeUri, { replace: true });
  };

  return (
    <Security oktaAuth={oktaAuth} restoreOriginalUri={restoreOriginalUri}>
      {children}
    </Security>
  );
};
```

### SDK Versions

@okta/okta-auth-js: 6.5.1
@okta/okta-react: 6.4.3

### Execution Environment

React 18.1.0
Chrome 101.0.4951.64

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
We are awaring of this.
Duplicates https://github.com/okta/okta-auth-js/issues/1174
