### ISSUE TITLE
If user clicks on browser back after login, SDK displays error in Login callback page

### ISSUE THREAD

**Issue by CauveryRaja25** [okta/okta-react#260]
### Describe the bug

When a user clicks on browser back after login, below error is displayed in login/callback page

> AuthSdkError: Could not load PKCE codeVerifier from storage. This may indicate the auth flow has already completed or multiple auth flows are executing concurrently.

**Approach**: okta-hosted-login

<img width="899" alt="Screenshot 2023-07-05 at 4 07 29 PM" src="https://github.com/okta/okta-react/assets/136563467/e77352ee-d3f3-4b30-af18-1717e9b53027">

### Reproduction Steps?

Consider if the user logs in as mentioned below

Navigates from A -> B (okta login page/ login callback) -> C
When back button is clicked from page C

**Current behaviou**r:
Navigates to page B - login callback page displaying the above error

**Expected behaviour**:
Since user is already logged in, skip page B and directly route to page A.

### SDK Versions

Okta React SDK Version: "6.7.0"

### Additional Information

Though we are using router.replace in _restoreOriginalUri_ callback, its just pushing (not replacing login/callback) into history

**Comment by denysoblohin-okta** [comment]
This error message on login callback page makes sense
`This may indicate the auth flow has already completed ..`

You can use your own HOC wrapper around `LoginCallback` like this:
```js
import { useOktaAuth, LoginCallback } from '@okta/okta-react';

const MyLoginCallback = (props) => {
  const { authState } = useOktaAuth();
  if (!authState.isAuthenticated) {
    return <LoginCallback {...props} />;
  } else {
    return "Auth flow has been already completed";
  }
}
```

**Comment by CauveryRaja25** [comment]
Thanks for responding. This approach will just display the above message instead of the error. But we don't want our users to see this page(login callback) since they've already logged in.

When user clicks browser back from `Dashboard` after login, currently the flow is 
`Home <- Login Callback <- Dashboard`
**Expected**: `Home <- Dashboard`

 Ideally the login callback should not be in history, it should be replaced but it isn't. Though we are using `history.replace()`, its not replacing the login callback

<img width="568" alt="image" src="https://github.com/okta/okta-react/assets/136563467/6f0b0695-54d2-4deb-9948-275a459bd990">


**Note**: We are able to reproduce the same behaviour in [Okta React Sample](https://github.com/okta/samples-js-react)

**Comment by jaredperreault-okta** [comment]
Can you provide the output of `npx envinfo --npmPackages '{@okta/*,react*}' --browsers`?

**Comment by denysoblohin-okta** [comment]
Actually, the history is:
`Home -> Okta Login Page -> Login Callback >> Dashboard`
`Login Callback` is replaced by `Dashboard` correctly if you use `restoreOriginalUri`.
When you go back in history, you go to `Okta Login Page` which redirects you to new `Login Callback` page with new `code` in url.
You can debug this with
```js
  oktaAuth.token.parseFromUrl._getHistory = () => {
    return {
      replaceState: (_: unknown, name: string, url: string) => {
        debugger
        history.replace(url);
      }
    } as any;
  };
```
AFAIK you can't remove `Okta Login Page` from the history

**Comment by CauveryRaja25** [comment]
Thanks for confirming. In that case, we'll add some user-friendly content in the `Login Callback page` for now. 
Feel free to let us know if this behaviour can be addressed/improved in the future.
