### ISSUE TITLE
authState returns invalid token in useOktaAuth hook

### ISSUE THREAD

**Issue by Roman-Kacharaba** [okta/okta-react#270]
### Describe the bug

Authorization token should be updated each time after "/token" request is sent. In useOktaAuth hook authState token value is outdated meanwhile in localStorage the token is already updated properly.
 
const { authState }: any = useOktaAuth();
authState - returns invalid value here after "/token" request is sent

### Reproduction Steps?

1) Wait few minutes until /token is called and token is refreshed with new value 
2) Right after it when calling useOktaAuth() hook, it returns outdated authState value, it doesn't match the token value in localStorage

### SDK Versions

System:
    OS: macOS 14.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 110.47 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.2
  npmPackages:
    @okta/okta-auth-js: ^7.2.0 => 7.5.0 
    @okta/okta-react: ^6.7.0 => 6.7.0 
    react: ^16.14.0 => 16.14.0 
    react-app-polyfill: ^3.0.0 => 3.0.0 
    react-dev-utils: ^12.0.1 => 12.0.1 
    react-dom: ^16.14.0 => 16.14.0 
    react-i18next: 11.16.4 => 11.16.4 
    react-redux: ^8.1.2 => 8.1.3 
    react-refresh: ^0.11.0 => 0.11.0 
    react-router-dom: 5.3.3 => 5.3.3

**Comment by jaredperreault-okta** [comment]
@Roman-Kacharaba were you able to reproduce this in a sample app?

**Comment by Roman-Kacharaba** [comment]
Not actual anymore
