### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by igloo12** [okta/okta-react#272]
### Describe the feature request?

There has been no releases since Sept 2022. No react router v6 yet. Are there plans to update this project or should people start migrating away? 

### New or Affected Resource(s)

Apps using react router v6

**Comment by guushamann** [comment]
I agree, also waiting on this to go forward to react router v6
especially interested in it to work with the new data api

**Comment by jaredperreault-okta** [comment]
No, this project is not dead. `okta-react` is a wrapper around `okta-auth-js`, which gets updated more frequently

**Comment by eddiemonge** [comment]
This should be reopened since it is dead. Maybe it should be handed over to the community, or more resources from Okta dedicated to updating it.
