### ISSUE TITLE
Release request for v6.8.0

### ISSUE THREAD

**Issue by mbeenen** [okta/okta-react#280]
### Describe the feature request?

Hi,

I'm hoping to pick up the change from https://github.com/okta/okta-react/commit/335defc2ee74a7ccbfa63ea9784c191b52094850, but it appears the latest version available via npm is still 6.7.0.

Is there any intent to publish 6.8.0?

### New or Affected Resource(s)

okta-react

**Comment by jaredperreault-okta** [comment]
6.8.0 has been released
