### ISSUE TITLE
3.0.6 to 3.0.8 - onAuthRequired not triggering

### ISSUE THREAD

**Issue by jchabotamica** [okta/okta-react#29]
updating from 3.0.6 to 3.0.8 onAuthRequired is no longer triggering.  Any guidance as to why?

Here's how we render our App:
![image](https://user-images.githubusercontent.com/52013619/98132296-38ab4280-1e8a-11eb-931d-279ca8ee83d9.png)

Here's the oktaConfig definition:
![image](https://user-images.githubusercontent.com/52013619/98132351-4e206c80-1e8a-11eb-8f59-cf6e2924f0dd.png)

**Comment by shuowu** [comment]
@jchabotamica I suspect it might because your `onAuthRequired` callback doesn't have access to `history` when it get called.

Can you try the [custom signIn sample](https://github.com/okta/samples-js-react/tree/master/custom-login) see if you still can reproduce the issue?

**Comment by jchabotamica** [comment]
@shuowu it actually looks like it is due to this check that was added to SecureRoute:
![image](https://user-images.githubusercontent.com/52013619/99267582-1f8f8380-27f2-11eb-90b5-f8e3467c2d54.png)

'match' is always null.  Not sure if this has to do with updates to history or what but doesn't seem to be accounting for the basename anymore.

**Comment by jchabotamica** [comment]
This can be closed
