### ISSUE TITLE
Minor README.md typo in "Replacing authService public methods" section

### ISSUE THREAD

**Issue by 1fifoto** [okta/okta-react#50]
Change 'orign' in

oktaAuth.signOut({ postLogoutRedirectUri: window.location.orign + '/goodbye' });

to 'origin' in

oktaAuth.signOut({ postLogoutRedirectUri: window.location.origin + '/goodbye' });

**Comment by shuowu** [comment]
@1fifoto Thanks for the reporting! #51 is opened to fix the typo.
