### ISSUE TITLE
Broken link between CHANGELOG and README

### ISSUE THREAD

**Issue by brockthebear** [okta/okta-react#57]
This line in [CHANGELOG](https://github.com/okta/okta-react/blob/master/CHANGELOG.md)
```md
- [#8](https://github.com/okta/okta-react/pull/8) See [MIGRATING](README#migrating-from-3x-to-4x) for detailed information.
```

needs to be changed to

```md
- [#8](https://github.com/okta/okta-react/pull/8) See [MIGRATING](README.md#migrating-from-3x-to-4x) for detailed information.
```

**Comment by brockthebear** [comment]
I tried pushing my changes to a new branch (`bb-fix-changelog-link`), but it looks like I don't have the correct access rights. An example of the error message I'm getting after `git push` is below.

```sh
> git push --set-upstream origin bb-fix-changelog-link
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by swiftone** [comment]
@brockthebear - Thanks for the help!  Our system requires outside contributors to request a PR from a branch on their own fork of our code rather than letting them create branches on our repo directly.

In this case, I'll make the change you've pointed later today - it's a useful fix, so thanks!

**Comment by brockthebear** [comment]
@swiftone  -- Ah, that makes sense. Thanks for letting me know! And no worries, I created a PR from a fork at this link #59

**Comment by shuowu** [comment]
PR merged
