### ISSUE TITLE
Expiry of ID tokens is not handled

### ISSUE THREAD

**Issue by andyrichardson** [okta/okta-react#75]
## About

When using an ID token, upon expiry of the token, okta-react's state doesn't change.

## Example

```tsx
// Inside of a secure route 
const state = useOktaAuth().authState;

/*
state has value
{
  isAuthenticated: true,
  isPending: false,
  idToken: 'some-initial-token',
}
*/

// After token expires
const state = useOktaAuth().authState;

/*
state has value
{
  isAuthenticated: true, // <- still true
  isPending: false,
  idToken: 'some-initial-token', // <- still outdated token
}
*/

```

### Expected result

The token in state is kept valid and is automatically refreshed prior to expiry.

### Actual result

The token in state never changes and expires without being refreshed.

### `idToken` state

 - Add an option for auto-renewal of tokens (default true - like `okta-js`
 - 1 minute prior to expiry, renew the idToken and update the state

### `isAuthenticated` state

 - change to false if the idToken and refresh token are expired (or even just the idToken?)
 - redirect to the login page if currently in a secure route
 
### okta-js by default auto-renews

Auto renew is enabled by default and there looks to be an event for renewal and expiry - https://github.com/okta/okta-auth-js#tokenmanageronevent-callback-context

### Why does this state exist

I'm not sure what the value is in having the token in state if it's not going to be kept in sync with the state of the app - it might be best to not include a token that will never change following the initial render.

### Expiring refresh tokens

In the case where a user's token and refresh token has expired, is it safe to assume the provided routing guards would not handle this condition?

## Okta deps
 - @okta-react@3.0.10
 - @okta-auth-js@3.2.6
 - @okta/configuration-validation@0.4.3
 - @okta-signin-widget@4.2.0

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for submission @andyrichardson.

It looks like the AuthState is [expected](https://github.com/okta/okta-auth-js/blob/4002e08fd104f103e28bd32c12cab9b6d39fba4b/test/spec/AuthStateManager.js#L218) to be in sync with token expiration.
I will try reproducing this to make sure I'm not missing any details.

**Comment by oleksandrpravosudko-okta** [comment]
@andyrichardson I tried running [sample app](https://github.com/okta/samples-js-react/tree/master/custom-login) with specified package versions - it didn't seem produce the described issue.

A few questions to help with further investigation:
* are you able to confirm through [introspect](https://developer.okta.com/docs/reference/api/oidc/#introspect) endpoint the expired token from AuthState is indeed inactive? Note: be sure to test against the same issuer which generated the token.
* аre there renew-related requests being fired (`/authorize`,  `/token`) upon token expiration?
* would it be possible for you to check if this issue persists when using latest package versions?

**Comment by andyrichardson** [comment]
Hey @oleksandrpravosudko-okta thanks for the response!

> are you able to confirm through introspect endpoint the expired token from AuthState is indeed inactive? Note: be sure to test against the same issuer which generated the token.

Yes, we check the token on the backend and it has passed it's expiry

> аre there renew-related requests being fired (/authorize, /token) upon token expiration?

No, there are no attempts to renew the token in the browser after it's expiry

> would it be possible for you to check if this issue persists when using latest package versions

Just started migrating now.

---

Can you point to the code where you expect the token to be updated in state?

From experimentation, it looks like the [place where we subscribe to authState updates](https://github.com/okta/okta-react/blob/master/src/Security.tsx#L57) will only trigger after okta state updates have been triggered. There are no calls to `tokenManager.get` or `tokenManager.renew` in the React library so I see no reason why the token will ever be refreshed if it is being retrieved synchronously from the provided React state.

This begs the question, why are tokens being exposed synchronously? Consuming them in this manner will cause them to expire without refresh.

---

I'm not sure if we're going to commit to this route yet but I've been just using the `okta-auth-js` library and it seems to be a bit more predictable (mainly because of no sync access to tokens).

```tsx
export const AuthProvider: FC = ({ children }) => {
  const [user, setUser] = useState<UserClaims | undefined | 'ERROR'>();
  const [authState, setAuthState] = useState({ isPending: true, isAuthenticated: false });

  const authClient = useMemo(
    () =>
      new OktaAuth({ // ...
    [],
  );

  useEffect(() => {
    // Subscribe to auth state on mount
    authClient.authStateManager.subscribe(setAuthState);

    // Update for initial render
    authClient.authStateManager.updateAuthState();

    // Check for changes to state every second (negligable cost - doesn't trigger API call, checks local storage)
    const interval = window.setInterval(() => authClient.authStateManager.updateAuthState(), 1000);
    return () => clearInterval(interval);
  }, [authClient]);

  // Handle token retrieval
  useEffect(() => {
    // Ignore if pending or authenticated
    if (authState.isPending || authState.isAuthenticated) {
      return;
    }

    // Store tokens if sourced from redirect
    if (authClient.token.isLoginRedirect()) {
      authClient.storeTokensFromRedirect();
      return;
    }

    authClient.token.getWithRedirect();
  }, [authState, authClient]);

  // Handle user object
  useEffect(() => {
    if (user || authState.isPending || !authState.isAuthenticated) {
      return;
    }

    authClient
      .getUser()
      .then(setUser)
      .catch((err) => {
        console.error(err);
        setUser('ERROR');
      });
  }, [user, authState, authClient]);

  // Pending auth check / redirecting to login / fetching user
  if (authState.isPending || !authState.isAuthenticated || user === undefined) {
    return (
      <PageSpinnerContainer>
        <Spinner />
      </PageSpinnerContainer>
    );
  }

  if (user === 'ERROR') {
    return (
      <>
        Error fetching user
        <a href="/">Reload</a>
      </>
    );
  }

  return <AuthContext.Provider value={{ authClient, user }}>{children}</AuthContext.Provider>;
};
```

**Comment by oleksandrpravosudko-okta** [comment]
> Can you point to the code where you expect the token to be updated in state?

In okta-auth-js and okta-react v3 token update in state appears to be triggered by token expiration event fired [here](https://github.com/okta/okta-auth-js/blob/f23a932b17c863c9f05db4809f9c1a86be3c572d/packages/okta-auth-js/lib/TokenManager.js#L73) and is [handled](https://github.com/okta/okta-react/blob/3.0/src/AuthService.js#L57) on okta-react side. `updateAuthState` handler invokes async token [getter](https://github.com/okta/okta-react/blob/3.0/src/AuthService.js#L131) with actual [renew](https://github.com/okta/okta-auth-js/blob/f23a932b17c863c9f05db4809f9c1a86be3c572d/packages/okta-auth-js/lib/TokenManager.js#L131) side effect.

In okta-react v4 token expiration handler is no longer present - it is moved to okta-auth-js (v4).

re: AuthProvider code - it looks like running scheduled `authClient.authStateManager.updateAuthState()` update might not be necessary - you should be able to get up-to-date auth state once subscribed to authStateManager updates.

**Comment by andyrichardson** [comment]
> In okta-auth-js and okta-react v3 token update in state appears to be triggered by token expiration event fired here and is handled on okta-react side.

Thanks - that's the part I was looking for - I'm not sure why it wasn't being called. Is it possible for the token is being set in state without calling `tokenManager.add`?

> it looks like running scheduled authClient.authStateManager.updateAuthState() update might not be necessary - you should be able to get up-to-date auth state once subscribed to authStateManager updates

Yeah I think you're right. We had something funky going on where localStorage was being cleared on the users device and the app would just crash - this is a workaround until we find the root cause.

**Comment by andyrichardson** [comment]
@oleksandrpravosudko-okta thanks for all the support so far 🙏 

Sorry to be a pain, I'm just not sure I'm properly understanding / confident in how sync auth tokens are being updated.

I've created an [example here](https://codesandbox.io/s/romantic-poitras-rjf3f?file=/src/index.js:405-509) that does the following:
 - Creates an okta-auth-js instance
 - Subscribes to the authStateManager
 - Updates the token with a token that will expire in 20s

Am I mistaken in assuming that there should be two state updates, one when the token is initially added and another after 20 seconds when the token has expired?

**Comment by oleksandrpravosudko-okta** [comment]
no problem at all @andyrichardson 

> Am I mistaken in assuming that there should be two state updates, one when the token is initially added and another after 20 seconds when the token has expired?

I believe you are not - AuthStateManager is expected to [handle](https://github.com/okta/okta-auth-js/blob/master/lib/AuthStateManager.ts#L54) token add event and token expiration event mentioned early should produce another update.

**Comment by andyrichardson** [comment]
> I believe you are not - AuthStateManager is expected to handle token add event and token expiration event mentioned early should produce another update.

In this example, I'm not seeing any kind of update following that 20s interval - is this a bug?

**Comment by oleksandrpravosudko-okta** [comment]
I'm trying to see what prevents this example from working as expected - will get back once I have more info.

**Comment by oleksandrpravosudko-okta** [comment]
It appears that successive idToken setting blocks expiration event firing - trying to pinpoint code causing that.

**Comment by oleksandrpravosudko-okta** [comment]
Not sure if this is intentional, but the expiration time of latter ID token in [example](https://codesandbox.io/s/romantic-poitras-rjf3f?file=/src/index.js:2039-2063) is set to +~16 minutes from initial execution time(i.e. adding 1000 seconds to unix timestamp). This introduced a false impression about expire event never being fired. With expiration time updated, token expiration event and renew attempt are triggered but execution does not get to the point where `updateAuthState` is triggered (no 'added' or 'removed' events are fired) because of renew-related API call failure(network requests results don't seem to visible in codesandbox?). I expect renew calls(and the subsequent `updateAuthState`) to complete successfully once missing routes and configuration are added to example app.

**Comment by andyrichardson** [comment]
> once missing routes and configuration are added to example app.

Routes are specific to the okta-react implementation, no? It seems like this should work regardless of any routing?

Let me know what configuration needs to be added and we can update the example to check!

**Comment by oleksandrpravosudko-okta** [comment]
You are right, routing is necessary here, pardon for confusion.

I was able to get the expected behaviour in the example [here](https://codesandbox.io/s/suspicious-http-nod33?file=/src/index.js) (modified copy of original example).

**Comment by andyrichardson** [comment]
> You are right, routing is not necessary here, sorry for confusion.
> 
> I was able to get the expected behaviour in the example [here](https://codesandbox.io/s/suspicious-http-nod33?file=/src/index.js) (modified copy of original example).
> 
> UPD: Note that access token expire->refresh doesn't trigger as it gets [cleared](https://github.com/okta/okta-auth-js/blob/eb7d70d902e1cccf767325dcbe3710d9f2da4be6/lib/TokenManager.ts#L319) before token renew request initiated by ID token expiration starts.

Thanks for the example - it does look like the new token, following expiry, is published.

Have you tried loading the sandbox and disabling network connections? 

It looks like we still have this issue where the token is expired and there's no event being triggered.

**Comment by oleksandrpravosudko-okta** [comment]
> Am I right in thinking we should instead have 4?

I believe no, not in this case. `First token added` state update gets [canceled](https://github.com/okta/okta-auth-js/blob/master/lib/AuthStateManager.ts#L115) and `Second token expired` doesn't trigger state update as its expire->renew callback is [cleared](https://github.com/okta/okta-auth-js/blob/eb7d70d902e1cccf767325dcbe3710d9f2da4be6/lib/TokenManager.ts#L319) when first token's renew is attempted.

**Comment by shuowu** [comment]
@andyrichardson FYI, okta-auth-js added active auto-renew since v4.0 (https://github.com/okta/okta-auth-js/blob/master/CHANGELOG.md#400), but looks like your app is still on v3.x, which does token renew in a passive way (renew will be triggered only when `tokenManager.get` is called). We do suggest upgrade the SDKs to our latest version (`okta-auth-js@4.x` & `okta-react@4.x`), then the auto-renew behavior should work for your app.

**Comment by andyrichardson** [comment]
Sounds good @shuowu :+1:
