### ISSUE TITLE
useOktaAuth hook giving undefined authService

### ISSUE THREAD

**Issue by daltonfury42** [okta/okta-react#79]
I followed the docs and have double checked, the component in which I am using the hook is wrapped inside `BrowserRouter->Security`, but the hook gives `undefined` for `authService` but `authState` is initialised.

I have isolated Okta integration into a minimal commit to reproduce the issue here:
https://github.com/SimplQ/simplQ-frontend/pull/481/commits/b18e4c78777fbc39bdccaa0501ed4b2ae30023c9

Console output:
![image](https://user-images.githubusercontent.com/11256376/105580561-105d2100-5db3-11eb-89e0-a6c929858090.png)

I might have missed something, can you help, please.

**Comment by oleksandrpravosudko-okta** [comment]
Hi @daltonfury42,

In okta-react v4 `authService` is replaced with `oktaAuth` (OktaAuth instance) - please see the [migration guide](https://github.com/okta/okta-react/blob/7bf0c587ae9fe118a92f94174b6c9721d2eaa5ab/README.md#replacing-authservice-instance)

**Comment by daltonfury42** [comment]
Thanks, got it. Please update your React doc here: https://developer.okta.com/docs/guides/sign-into-spa/react/add-signin-button/

**Comment by shuowu** [comment]
Internal Ref: OKTA-364061

**Comment by efreila** [comment]
Documentation is outdated here as well: https://developer.okta.com/docs/guides/sign-into-spa/react/user-info/

**Comment by Sanjotarm** [comment]
authState and authService both giving undefined. 

Currently using  "@okta/okta-react": "3.0.4",

Any comments on this.

**Comment by shuowu** [comment]
@Sanjotarm Have you wrapped your app with the `<Security>` component before using `authState` and `authService`. 

You can check [samples for v3.x](https://github.com/okta/samples-js-react/tree/ac54c7d272e8d36c4d4fe95a328471fd82100f3d) for implementation details.

**Comment by daltonfury42** [comment]
I ended up using auth0 and it's been a good experience
