### ISSUE TITLE
Unable to add <Security/> provider inside @reach/router <Router />

### ISSUE THREAD

**Issue by stevenmckinnon** [okta/okta-react#81]
Hi,

I'm trying to migrate from v3 to v4.1.0 and it's causing me issues with trying to put the Security provider inside **@reach/router**'s `<Router />` provider.

```
import { Router } from "@reach/router";
import { Security, LoginCallback } from "@okta/okta-react";
import { oktaAuth } from "./utils/oktaConfig";
import Home from "./pages/Home";

<Router>
  <Security oktaAuth={oktaAuth}>
    <LoginCallback path="/login/callback" />
      <Home path="/" />
  </Security>
</Router>
```

I'm getting an error saying that says:
```
Children of <Router> must have a `path` or `default` prop, or be a `<Redirect>`
```

Moving Security outside of Router breaks the login callback as it can't access history.

![image](https://user-images.githubusercontent.com/32041213/106173163-8b478280-618b-11eb-926a-a1675ea82dd8.png)

Apologies if I've missed something obvious, but any help is appreciated.

|  Package | Version  |
|---|---|
| @okta/okta-react  | 4.1.0  | 
| @okta/okta-auth-js  | 4.9.1  |  
| @reach/router  | 1.3.4  |

**Comment by shuowu** [comment]
@stevenmckinnon Thanks for reporting the issue. We have a PR (https://github.com/okta/okta-react/pull/71) to decouple react-router module from the `Security` component, it will be released in the next major version.

Meanwhile, as a workaround, you can install the `react-router-dom` (the bundler should be able to tree shake away the unused module for you) and provide the custom [restoreOriginalUri](https://github.com/okta/okta-auth-js#restoreoriginaluri) callback when initialize the oktaAuth.instance.

**Comment by shuowu** [comment]
Related to https://github.com/okta/okta-oidc-js/issues/910

**Comment by stevenmckinnon** [comment]
Thanks that works for me just now. 

I'll keep an eye out for releases.

**Comment by manishie** [comment]
I'm having the same issue, but I'm not exactly sure how to implement the workaround.  I installed react-router-dom, and here's my app:

```
import React from "react";
import { Router } from "@reach/router";
import Home from "../components/home/home";

import { LoginCallback, SecureRoute, Security } from "@okta/okta-react";
import { OktaAuth } from "@okta/okta-auth-js";

export default function App() {
  const oktaAuth = new OktaAuth({
    issuer: "https://****.okta.com/oauth2/default",
    clientId: "*****",
    redirectUri: window.location.origin + "/callback",
    restoreOriginalUri: (_, originalUri) => {
      window.location.replace(originalUri);
    },
  });

  return (
    <Router>
      <Security oktaAuth={oktaAuth}>
        <SecureRoute path="/private" exact={true} component={Home} />
        <LoginCallback path="/callback" />
      </Security>
    </Router>
  );
}
```

@stevenmckinnon could you paste your working code, or @shuowu could you provide some more info?  Thank you!

**Comment by denysoblohin-okta** [comment]
@manishie 
1. You need to make `<Security>` root component and put `<Router>` inside it. Like
```js
  <Security oktaAuth={oktaAuth}>
    <Router>
      <LoginCallback path="/callback" />
    </Router>
  </Security>
```
2. You can't use `SecureRoute` together with `@reach/router` as it depends on `react-router` and renders `react-router`'s `Route`.

**Comment by manishie** [comment]
@denysoblohin-okta thanks I tried that but it didn't work.  Now I get a completely blank screen.  No errors in the browser, in the JS console or in the dev server.  

I had been trying to follow the @shuowu's workaround which suggested doing something like I had tried.
