### ISSUE TITLE
Login via the Okta dashboard does not work

### ISSUE THREAD

**Issue by Mansari** [okta/okta-react#84]
Hi. If I allow my application to accept logins from the App or Okta (in the application General Settings section on Okta), then following the application chiclet link from the Okta Dashboard results in a blank page (the `login/callback` redirect).

Do I have something misconfigured or is this not supported similar to the social logins?

Are there plans to support social login or at least instructions on how to implement this or the case above if we wanted to fork the repo and edit the LoginCallback component ourselves?

Thanks for an amazing plugin!

**Comment by aarongranick-okta** [comment]
@Mansari Thanks for your question on using `okta-react` with an application launched through the chiclet link. I will have to do some more research on this and get back to you.

As for [social login](https://developer.okta.com/docs/concepts/social-login/), this is currently supported using the [custom domain](https://developer.okta.com/docs/guides/custom-url-domain/enable-the-custom-domain/) feature. Or you can construct authorization links manually using instructions here: https://developer.okta.com/docs/concepts/social-login/
and here: https://github.com/okta/okta-signin-widget#openid-connect

**Comment by Mansari** [comment]
Hi @aarongranick-okta - wondering if you had any luck finding anything related to this? or maybe doing some testing on your end to see if it is our use of the plugin or our app deployment method that is causing it not to work?

**Comment by aarongranick-okta** [comment]
@Mansari I'm sorry I have not been able to further investigate this yet. 

Can you see what parameters are passed to the login callback (are you receiving a code or access_token?). The `okta-react` library is designed to work with the SPA application type, but if the URL contains `code` that means it is expecting a server-side handler (web application type with authorization code / client secret).

I also believe you will need to disable `pkce` for this type of flow to work (to receive tokens directly on the callback with no previous interaction)

We are aware of an issue in `okta-react` where errors are not displayed on the callback component, but you should be able to determine what if any errors are being returned by looking at the network responses for `/authorize` and `/token`.

I have created an internal issue: OKTA-370059
I am hoping we will be able to resolve this for you quickly.

**Comment by aarongranick-okta** [comment]
@Mansari Thinking about this further, I believe you are already authenticated when you hit the chiclet. So the app on this special inbound route should use `oktaAuth.token.getWithoutPrompt` to retrieve tokens from the existing SSO session.  This route should probably NOT be the same as used for the OAUTH redirect (`/login/callback`). Maybe a page like `/login/sso`, I think you should be able to configure this with the chiclet?

**Comment by Mansari** [comment]
Thanks Aaron. I'll try this.

In this case would I handle the SSO route myself in the app? Right now the
callback route is handled within the plug-in itself so I imagine I need to
do similar code but for the sso page?

**Comment by Mansari** [comment]
@aarongranick-okta I think I found the issue. In configuring the chiclet it has two options:

1. Redirect user when you click on an application logo to go a to a page to login. I had the callback URL there which does not make sense, it should be the login page for users to reinitiate login. This is OIDC compliant.
2. Send the `id_token` to a page of your choosing since the user is already authenticated. This is called Okta Simplified flow. In this case the `id_token` is passed as a query parameter that I can 'catch' on my end and set internally. I won't have an access token though, so wondering what can I do to retrieve one at this point using the react plugin or the auth-js sdk.

Any thoughts are appreciated, otherwise I will think about it more and read on the docs.

**Comment by Mansari** [comment]
I managed to resolve this by adding another route (`/sso` for example) that does a `oktaAuth.signInWithRedirect` using the Okta React plugin.

I now setup my chiclet in the Okta Dashboard to `Redirect to app to initiate login (OIDC Compliant)` and point the `Initiate login URI` to the new `/sso` route I have. The SPA will now execute that flow and since the user already has a session will redirect to our app just fine.

Impressive stuff and perhaps we can add to the Readme.md as another use case perhaps.
