### ISSUE TITLE
Client side user registration 

### ISSUE THREAD

**Issue by ericlifs** [okta/okta-react#86]
This is not an issue but a question instead.

Is there a way of sign up users from the client side? I have seen [this endpoint](https://developer.okta.com/docs/reference/api/users/#create-user-with-password) on okta's api documentation for creating users but we don't have the feature on `okta-react` or `okta-react-native`. Is there a reason to that? Therefore is backend-side the only way of creating users?

Thanks!

**Comment by swiftone** [comment]
The endpoint you link to cannot be used from the browser-side (at least, not yet).   That endpoint will currently reject browser-based requests with CORS errors, though there is work to modify that.  Even then, using that endpoint would require authentication, so it is only appropriate if you are looking to create an administrator dashboard.

An alternative is allowing users to create accounts themselves, using Self Service Registration.  This CAN be done using our SignIn Widget on the client-side.   I suggest talking to our support staff at developers@okta.com to cover the various nuances and policy settings required for that.

If you're looking to use the endpoint you listed to create users, we have a number of backend SDKs to make use of our management APIs, such as 

- https://github.com/okta/okta-sdk-nodejs
- https://github.com/okta/okta-sdk-java
- https://github.com/okta/okta-sdk-dotnet
- https://github.com/okta/okta-sdk-golang
- https://github.com/okta/okta-sdk-php
- https://github.com/okta/okta-sdk-python

Note these are our "Management" SDKs (to manage users/groups/policies/etc) as opposed to our "Authentication" SDKs (to perform actual logins and related authentications)

**Comment by ericlifs** [comment]
Oh sorry, I forgot to mention I'm not using the SignIn Widget on the frontend. I have just implemented the custom sign-in form and I was wanting to know if there is a similar way of doing the registration form. Sounds like the only option will be creating a small server to accomplish this.

Thanks @swiftone!

**Comment by shuowu** [comment]
Close the issue. Feel free to reopen it if further questions exist.
