### ISSUE TITLE
LoginCallback doesn't set token after redirect

### ISSUE THREAD

**Issue by stevenmckinnon** [okta/okta-react#87]
We are facing a similar issue to this one reported on the @okta/okta-auth-js library ([issue 610](https://github.com/okta/okta-auth-js/issues/610)), after the user successfully logs in, the **/login/callback** path isn’t saving the auth token immediately, therefore the front end still thinks the user is unauthenticated, and navigates back to the login page. There’s also a warning in the console: 

> [okta-auth-sdk] WARN: updateAuthState is an asynchronous method with no return, please subscribe to the latest authState update with authStateManager.subscribe(handler) method before calling updateAuthState.

After re-clicking login or refreshing the page, it is now able to see the auth token in local storage and works as intended. 

Here’s a stripped-down version of our App.tsx:
```
function App() {
  const onAuthRequired = () => {
    history.push("/login");
  };

  const oktaAuth = new OktaAuth({
    ...Config.okta,
    redirectUri: `${window.location.origin}/login/callback`,
  });

  return (
    <Security oktaAuth={oktaAuth} onAuthRequired={onAuthRequired}>
      <Route path="/login/callback" component={LoginCallback} />
      <Route path="/login" component={LandingPage} />
      <SecureRoute exact path="/" component={Home} />
    </Security>
  );
}

```
Note: We’re using the Okta page for login and navigating to it with the following function: 
```
  const handleLogin = () => {
    oktaAuth.signInWithRedirect();
  };
```

Any advice would be appreciated! 

```
   "@okta/okta-auth-js": "^4.7.1",
    "@okta/okta-react": "^4.1.0",
```

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for report @stevenmckinnon.

Does this issue occur intermittently (as in #610)?
In case it doesn't - would you be able to check if providing explicit original URI makes any difference?
```javascript
oktaAuth.signInWithRedirect({
  originalUri: `${window.location.origin}`,
});
```

**Comment by stevenmckinnon** [comment]
Hey @oleksandrpravosudko-okta thanks for the quick response. 

The issue is consistent unfortunately. 

Providing the original URI has the same issue.

**Comment by aarongranick-okta** [comment]
@stevenmckinnon It is very important that while the callback is executing, no other logic is happening simultaneously. The auth flow is *in progress* and needs to do a token exchange that is asynchronous.  The most common cause of this error in React is multiple components rendering on a route. The culprit in this case may be the "Landing" component which is set on the path `/login/`. The default behavior of React router would be to also render this "Landing" component on the callback page, because it matches the path `/login/*` (there is an implicit wildcard after each path).  Landing and LoginCallback executing simultaneously may be creating this race condition.

We recommend wrapping your routes in a `<Switch>` component so that only one will render and/or using the `exact` keyword on any routes which may overlap with the callback (in this case / and /login)

**Comment by stevenmckinnon** [comment]
Sorry, that was my mistake when trying to stream-line our code, we do in fact have the `<Switch />` wrapper.

**Comment by aarongranick-okta** [comment]
@stevenmckinnon From your original post:

`the front end still thinks the user is unauthenticated, and navigates back to the login page`

It sounds like this "front end"  is the code that is engaged in a race with the callback. Do you know exactly where this redirect logic is being triggered? Somehow this code must be made to not run when on the callback route.

**Comment by stevenmckinnon** [comment]
@aarongranick-okta What I've shared is the only logic we have relating to login with Okta.

- User clicks `oktaAuth.signInWithRedirect();`
- Logs in using the Okta login page
- Redirects to `/login/callback`
- I can see the token amended on the the `/login/callback` path 
- It then redirects to `/login`
- rechecking login or refreshing logs proceed to the expected logged in user path i.e. `/`

[Here's a gif for reference](https://gfycat.com/angelicinexperiencedindianpangolin)

**Comment by aarongranick-okta** [comment]
@stevenmckinnon 
It's possible that something has gone wrong with the `originalUri`. This is the URI to redirect to after the callback has been handled. 

It can be set directly, `oktaAuth.setOriginalUri`, or passed as a parameter to `signInWithRedirect` as @oleksandrpravosudko-okta [commented](https://github.com/okta/okta-react/issues/87#issuecomment-783422376)
https://github.com/okta/okta-auth-js/blob/master/lib/browser/browser.ts#L316

When the callback is being handled, the `originalUri` value is read and used for redirect
https://github.com/okta/okta-auth-js/blob/master/lib/browser/browser.ts#L545

`handleLoginRedirect` should redirect to `window.location.origin` by default, unless an `originalUri` was set or `restoreOriginalUri` was set to false.
 
Based on the code you've shared, I don't understand why it would redirect to `/login` after the callback is handled - unless the SecureRoute thinks you are not authenticated (and calls `onAuthenticated`). Is there logic in the `Home` component to redirect or call `onAuthenticated`? Can you set a `debugger` in your onAuthenticated method? Is it being called by the SecureRoute after a redirect to `/` from `handleLoginRedirect`?  

I tried to recreate this scenario using [the react sample](https://github.com/okta/samples-js-react/tree/master/custom-login) with no luck. (I used `showSignInAndRedirect`)

**Comment by stevenmckinnon** [comment]
@aarongranick-okta, 

I found the route cause, there was a component wrapped around the app that was trying to push to a secure route without checking if the user was authenticated or not, and this was happening before the authState was being set correctly which was pushing the app back to the login page.

Appreciate your help!
