### ISSUE TITLE
okta-react doesn't provide any way to do error handling

### ISSUE THREAD

**Issue by distinctdan** [okta/okta-react#91]
I've trying to use okta-react for my app's login, but it appears to be silently eating errors. I've configured my app to use the LoginCallback component, and I'm using `oktaAuth.signInWithRedirect('/');` to log in. My okta configuration policy isn't complete yet, so after logging in, I get redirected back to my app's callback url with an error. However, the LoginCallback component doesn't show any error, and instead redirects to my initial login page. Also, there aren't any error properties being set in `authState` from `const {oktaAuth, authState} = useOktaAuth()`;

I need one of the following in order to be able to use okta-react at all:
- The LoginCallback component should show an error instead of silently redirecting back to my login page.
- `authState` should contain error properties to show that our state is `error` and a message that I can show to a user.

Here's my app routing:
```
const oktaAuth = new OktaAuth({
    issuer: process.env.REACT_APP_OKTA_ISSUER,
    clientId: process.env.REACT_APP_OKTA_CLIENT_ID,
    redirectUri: window.location.origin + '/login/callback',
});

export function App(props) {
    return (
        <div className="mainContainer">
            <Security oktaAuth={oktaAuth}>
                <Route path='/login' exact component={Login} />
                <Route path='/implicit/callback' exact component={LoginCallback} />
                <SecureRoute path='/' exact component={Home} />
            </Security>
        </div>
    );
}
```

**Comment by aarongranick-okta** [comment]
@distinctdan We are aware of this issue and are currently working on a fix. There is a workaround available: https://github.com/okta/okta-oidc-js/issues/926#issuecomment-761290513

**Comment by distinctdan** [comment]
Thanks for the info, that should work in the meantime.
