### ISSUE TITLE
README has typos for _oktaAuth

### ISSUE THREAD

**Issue by mraible** [okta/okta-react#97]
For example:

```
class App extends Component {
  constructor(props) {
    super(props);
    this.oktaAuth = new OktaAuth({
      issuer: 'https://{yourOktaDomain}.com/oauth2/default',
      clientId: '{clientId}',
      redirectUri: window.location.origin + '/login/callback'
    });
    this.restoreOriginalUri = async (_oktaAuth, originalUri) => {
      props.history.replace(toRelativeUrl(originalUri, window.location.origin));
    };
  }
```

`this.restoreOriginalUri` has `_oktaAuth` when it should have `oktaAuth`.

**Comment by denysoblohin-okta** [comment]
Underscore means oktaAuth param is not used

**Comment by mraible** [comment]
Is this a convention I'm not aware of? Can you please provide more information?

**Comment by swiftone** [comment]
You may have seen it also as `(_, someVal) => { ... }` - When a callback is called with a param, but we don't actually USE that param (and yet we use a later param in the signature), the underscore is often used to indicate that.

An alternative in JS is just to have no variable name and just have the comma, but that often looks much more like a typo.
